#%RAML 1.0 Trait
queryParameters:
      number1:
        required: true
        type: integer
      number2:
        required: true
        type: integer

responses:
      400:
        body:
          application/json:
            example:
              {
                "message": "bad request"
              }        
      401:
        body:
          application/json:
            example:
              {
                "message": "un auth"
              }
      500:
        body:
          application/json:
            example:
              {
                "message": "un auth"
              }